# Generated by Django 5.2 on 2025-05-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_remove_hotel_amenities_remove_hotel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
    ]
