# Generated by Django 5.2 on 2025-05-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_hotel_base_price_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(choices=[('standard', 'Chambre Standard'), ('deluxe', 'Chambre Deluxe'), ('presidentielle', 'Suite Présidentielle')], max_length=50),
        ),
    ]
